### ISSUE TITLE
Update seems to be broken

### ISSUE THREAD

**Issue by JSylvia007** [fHDHR/fHDHR_plugin_origin_ceton#47]
Howdy all!  Been a while.  I haven't been using Live TV for a while, but I was in the process of updating things in my environment, and fHDHR was one of those things.  

I did a git pull in the main fHDHR directory (that fast-forwarded, all good, no warnings), then I did the same in each of the plugin directories, (), again, all good no issues.

Kicked off fHDHR, started without an issue, clicked around, and everything seemed to be working.

When I clicked the "Ceton" button, the website says, "Internal Server Error", and the log dumps this out:

```
Traceback (most recent call last):
  File "/opt/fHDHR/lib/python3.8/site-packages/gevent/pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "/opt/fHDHR/lib/python3.8/site-packages/gevent/pywsgi.py", line 917, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/fHDHR/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/fHDHR/fHDHR/plugins/fHDHR_plugin_origin_ceton/web/ceton_html.py", line 31, in __call__
    return self.get(*args)
  File "/opt/fHDHR/fHDHR/plugins/fHDHR_plugin_origin_ceton/web/ceton_html.py", line 65, in get
    origin_status_dict["Tuner"+str(i)]['Device'] = int(self.plugin_utils.origin_obj.tunerstatus[str(i)]['ceton_device'])
KeyError: '4'
```

Any help?

**Comment by JSylvia007** [comment]
UPDATE: New config parameter required.  There is now a device_tuners and a tuners parameter.  I've set them both to 6, and now the page loads properly.

Plex can no longer stream, however, I now get this error in the log:

```
[2022-11-22 11:29:10,276] INFO - [ceton] Selected Ceton tuner#: 1
[2022-11-22 11:29:10,278] INFO - [ceton] Ceton tuner 1 to be started
[2022-11-22 11:29:10,467] INFO - [ceton] Preparing Ceton tuner 1 on port: 49991
[2022-11-22 11:29:11,396] INFO - [ceton] Initiate streaming channel 1412 from Ceton tuner#: 1
[2022-11-22 11:29:11,399] INFO - Attempting to Select an available tuner for this stream.
[2022-11-22 11:29:11,400] INFO - Tuner #1 Acquired.
[2022-11-22 11:29:11,402] INFO - ceton Tuner #1 to be used for stream.
[2022-11-22 11:29:11,404] INFO - Preparing Stream...
[2022-11-22 11:29:11,405] ERROR - Unable to Stream: TunerError: Tuner Setup Failed (lazily handled): Tuner Setup Failed (lazily handled):KeyError 'buffsize'- /opt/fHDHR/fHDHR/fHDHR/streammanager/stream/__init__.py line 81
[2022-11-22 11:29:11,415] INFO - 10.1.60.99 - - [2022-11-22 11:29:11] "GET /api/tuners?method=stream&channel=855&origin=ceton&stream_method=ffmpeg&accessed=http%3A//10.1.60.99%3A5004/hdhr/ceton/auto/v855 HTTP/1.1" 503 2648 1.696196
```
